import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedsucursalwidget4/generated/GeneratedMapWidget5.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedsucursalwidget4/generated/GeneratedFrame4Widget.dart';

/* Frame Sucursal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSucursalWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 255, 255, 255),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 140, 140, 140),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 816.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 80.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: -49.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 512.0,
                height: 512.0,
                child: GeneratedMapWidget5(),
              )
            ]),
      ),
    ));
  }
}
