import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedTelmex1Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedBienvenidoalserviciotecnicodeTelmexWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedGroup2Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 600.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 368.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 146.0,
                child: GeneratedTelmex1Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 64.0,
                child: GeneratedBienvenidoalserviciotecnicodeTelmexWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 781.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: GeneratedGroup3Widget(),
              )
            ]),
      ),
    ));
  }
}
