import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedajusteswidget2/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedajusteswidget2/generated/GeneratedFrame2Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedajusteswidget2/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedajusteswidget2/generated/GeneratedGroup11Widget.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 255, 255, 255),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 140, 140, 140),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 816.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 80.0,
                child: GeneratedFrame2Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 114.0,
                child: GeneratedGroup11Widget(),
              )
            ]),
      ),
    ));
  }
}
