import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciowidget1/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciowidget1/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciowidget1/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciowidget1/generated/GeneratedGroup8Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 255, 255, 255),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 140, 140, 140),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 816.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 80.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 60.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 60.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 60.0,
                child: GeneratedGroup8Widget(),
              )
            ]),
      ),
    ));
  }
}
